name: dokan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  zoom_tap_animation: ^1.1.0
  cupertino_icons: ^1.0.6
  dio: ^5.2.1+1
  font_awesome_flutter: ^10.7.0
  flutter_spinkit: ^5.1.0
  get_storage: ^2.0.3
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  # flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:

    - assets/images/
  uses-material-design: true

